const REGISTER = "REGISTER";
const LOGIN = "LOGIN";
const GETUSERLIST = "GETUSERLIST";
const ISLOGIN = "ISLOGIN";
const ADDUSER = "ADDUSER";
const DELETEUSER = "DELETEUSER";
const EDITUSER = "EDITUSER";

export { REGISTER, LOGIN, GETUSERLIST,ISLOGIN,ADDUSER,DELETEUSER,EDITUSER};